name: Run Telegram Bot

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc python3-dev

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Sync time
        run: |
          sudo date -s "$(curl -s --head http://worldtimeapi.org/api/timezone/Etc/UTC | grep Date: | sed 's/Date: //g')"

      - name: Run the bot
        run: |
          python -m AnonXMusic
