name: Run Telegram Bot

on:
  push:
    branches:
      - main  # سيعمل عند أي تحديث على الفرع الرئيسي
  workflow_dispatch:  # لإمكانية تشغيله يدويًا من GitHub Actions

jobs:
  run-bot:
    runs-on: ubuntu-latest  # يستخدم بيئة Ubuntu

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2  # لجلب الكود من المستودع

      - name: Set up Python
        uses: actions/setup-python@v2  # إعداد بيئة بايثون
        with:
          python-version: '3.9'  # استخدم إصدار بايثون المناسب

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc python3-dev  # تثبيت المكتبات المطلوبة

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # تأكد من وجود هذا الملف ويحتوي على المكتبات

      - name: Run the bot
        run: |
          python -m AnonXMusic  # استخدم اسم المجلد الصحيح لتشغيل البوت
